### ISSUE TITLE
Fresh npm install fails

### ISSUE THREAD

**Issue by pr0pelh4t** [findy-network/findy-wallet-pwa#337]
When running npm i on freshly cloned repo the installation fails due to react-qr-reader. There is an open issue in their github https://github.com/react-qr-reader/react-qr-reader/issues/239. Also, the library seems somewhat abandoned - so it might be good to look for an alternative.

However, this issue can be fixed for the current setup by adding:

"overrides": {
    "react-qr-reader": {
      "react": "$react",
      "react-dom": "$react-dom"
    }
 }

to package.json.

**Comment by lauravuo** [comment]
Thanks for the issue and the solution proposal! I have also followed the issue you mentioned and saw the workaround suggestion. It's good to know that it works, I need to integrate it ASAP.

It seems that we don't have much time nowadays to dedicate enough TLC to this pwa app, but surely it would be a good idea to find a replacement for the current QR-reader library.
