### ISSUE TITLE
Register error

### ISSUE THREAD

**Issue by thapld** [findy-network/findy-wallet-pwa#795]
![image](https://github.com/findy-network/findy-wallet-pwa/assets/38736191/5cf9f141-894c-4f35-9387-b33874fe47a2)

1. I change cor config origin to *
2. Remove credentials: 'include' in reactjs client
3. Make register but error when call request attestation/result
![image](https://github.com/findy-network/findy-wallet-pwa/assets/38736191/aa83d457-985b-4b94-8df7-8ade0da72eac)

**Comment by lauravuo** [comment]
Matching origin is a security requirement in WebAuthn protocol. See specification here: https://www.w3.org/TR/webauthn-2/
